server:
  port: 2222

spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/ratings_db
    username: postgres
    password: j@vacefer2005
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

redis:
  server:
    urls: redis://localhost:6379
client:
  urls:
    ms-auth: http://localhost:9999



